services:
  hamlog:
    build: .
    container_name: hamlog
    ports:
      - "5050:5000"
    volumes:
      - ./app/data:/app/app/data
      - ./app/uploads:/app/app/uploads
    restart: unless-stopped
